apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
      - name: articles-container
        image: mngouhouo/mngouhouo:articles
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000 # Specify a node port here
  selector:
    app: articles

