apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19
  template:
    metadata:
      labels:
        app: covid19
    spec:
      containers:
      - name: covid19-container
        image: mngouhouo/mngouhouo:covid19
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: covid19-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000 # Specify a node port here
  selector:
    app: covid19

