apiVersion: apps/v1
kind: Deployment
metadata:
  name: halloween-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halloween
  template:
    metadata:
      labels:
        app: halloween
    spec:
      containers:
      - name: halloween-container
        image: mngouhouo/mngouhouo:halloween
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: halloween-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30000 # Specify a node port here
  selector:
    app: halloween

